name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Branch
        if: ${{ github.event.issue.pull_request }}
        #https://github.com/marketplace/actions/pull-request-comment-branch
        uses: xt0rted/pull-request-comment-branch@v1 
        id: comment-branch
      - name: Slash Command Dispatch
        id: dispatch
        if: ${{ github.event.issue.pull_request }}
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT_WORKFLOW }}
          commands: |
            run
          dispatch-type: workflow
          issue-type: pull-request
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            repoReference=${{ steps.comment-branch.outputs.head_ref }}
            ref=${{ steps.comment-branch.outputs.head_ref }}
            issue-number=${{ github.event.issue.number }}
            actor=${{ github.actor }}
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - name: Comment Run Id
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT_WORKFLOW }}
          repository: ${{ github.repository }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}
      - name: Edit comment with error message
        if: steps.dispatch.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.dispatch.outputs.error-message }}
          